name: Build and Deploy via IAM + SSM

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: yuvan77/carweb-static-test
  CONTAINER_NAME: carweb
  AWS_REGION: eu-north-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::899956062409:role/GitHub-ECR-Access
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Versioned Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy via SSM
        run: |
          IMAGE_TAG=${{ github.sha }}

          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy new docker version" \
            --parameters commands="
              docker pull $IMAGE_NAME:$IMAGE_TAG
              docker stop $CONTAINER_NAME || true
              docker rm $CONTAINER_NAME || true
              docker run -d \
                --name $CONTAINER_NAME \
                -p 80:80 \
                --restart always \
                $IMAGE_NAME:$IMAGE_TAG
              docker image prune -f
            " \
            --region $AWS_REGION
